FROM eu.gcr.io/support-prev-eslm/github.com/adeo/lmes-docker-base-images/base-frontend-npm-12-builder as builder
FROM eu.gcr.io/support-prev-eslm/github.com/adeo/lmes-docker-base-images/base-frontend-nginx-runner:latest
